/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Hp
 */
public class Sales extends javax.swing.JFrame {

    /**
     * Creates new form Sales
     */
    public Sales() {
        initComponents();
        connection();
        tabledata();
    }
    
    
    
    Connection con;
    PreparedStatement pst;
    public void connection(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/shop", "root","");
            System.out.println("connecting");
        }catch (ClassNotFoundException ex) {
           ex.printStackTrace();
        }
        catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    public void tabledata(){
         try{
            pst=con.prepareStatement("select * from proreg");
           ResultSet rs=pst.executeQuery();
            DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
              tbmodel.setRowCount(0);
           while(rs.next()){
               String idk= String.valueOf(rs.getInt("id"));
               String pnamek=rs.getString("pname");
               String brpricek=String.valueOf(rs.getInt("brprice"));
               String slpricek=String.valueOf(rs.getInt("sellingprice"));
               String quantityk=String.valueOf(rs.getInt("quantity"));
               
               String tbdat[]={idk,pnamek ,quantityk,brpricek,slpricek};
              
               tbmodel.addRow(tbdat);
              
           }
            
        }catch(Exception e){
        
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txt1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        btnu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\ezgif.com-gif-maker (9).gif")); // NOI18N
        jLabel1.setText("Sales");

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setForeground(new java.awt.Color(0, 0, 156));
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\ezgif.com-gif-maker (6).gif")); // NOI18N
        jButton5.setText("goback");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setForeground(new java.awt.Color(0, 0, 156));
        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\ezgif.com-gif-maker (7).gif")); // NOI18N
        jButton6.setText("product registration");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jButton5)
                .addComponent(jButton6))
        );

        jTable1.setBackground(new java.awt.Color(0, 0, 156));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "product name", "quantity", "brought price", "Selling price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "product name", "price"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 156));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\ezgif.com-gif-maker (5).gif")); // NOI18N
        jButton1.setText("add the items to selling table");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 156));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\ezgif.com-gif-maker (4).gif")); // NOI18N
        jButton2.setText("Calculate the totalve value");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Total value:");

        lbl1.setText("0");

        jLabel3.setText("Balance:");

        jLabel4.setText("Answer wil display here");

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setForeground(new java.awt.Color(0, 0, 156));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\ezgif.com-gif-maker (2).gif")); // NOI18N
        jButton3.setText("refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setText("enter the amount given");

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setForeground(new java.awt.Color(0, 0, 156));
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\ezgif.com-gif-maker (4).gif")); // NOI18N
        jButton4.setText("calculate the balance");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        area.setColumns(20);
        area.setRows(5);
        jScrollPane3.setViewportView(area);

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setForeground(new java.awt.Color(0, 0, 156));
        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\ezgif.com-gif-maker (16).gif")); // NOI18N
        jButton7.setText("Generate receipt");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setForeground(new java.awt.Color(0, 0, 156));
        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\ezgif.com-gif-maker (15).gif")); // NOI18N
        jButton8.setText("print");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        btnu.setBackground(new java.awt.Color(255, 255, 255));
        btnu.setForeground(new java.awt.Color(0, 0, 156));
        btnu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\ezgif.com-gif-maker (18).gif")); // NOI18N
        btnu.setText("unselect");
        btnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnu))
                    .addComponent(jButton4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton3)
                                    .addComponent(btnu))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(32, 32, 32)
                                        .addComponent(jButton2)
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(lbl1)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(219, 219, 219)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(34, 34, 34)
                                .addComponent(jButton4))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(109, 109, 109)
                                .addComponent(jButton7)
                                .addGap(95, 95, 95))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton8)
                                .addGap(96, 96, 96))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        TableModel model1= jTable1.getModel();
        int [] index=jTable1.getSelectedRows();
        Object[] row=new Object[4];
   
        DefaultTableModel model2=(DefaultTableModel)jTable2.getModel();
        for(int i=0;i<index.length;i++){
            row[0]=model1.getValueAt(index[i], 0);
            row[1]=model1.getValueAt(index[i], 1);
            
              row[2]=model1.getValueAt(index[i], 4);
            model2.addRow(row);
        try{
           pst=con.prepareStatement("update proreg set  quantity=quantity-1 where id=?");
           pst.setString(1, model1.getValueAt(index[i], 0).toString());
          
           pst.executeUpdate();
       }catch(Exception e){
           
       }
       
        }
       
          
        try{
            pst=con.prepareStatement("select * from proreg");
           ResultSet rs=pst.executeQuery();
            DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
              tbmodel.setRowCount(0);
           while(rs.next()){
               String idk= String.valueOf(rs.getInt("id"));
               String pnamek=rs.getString("pname");
               String brpricek=String.valueOf(rs.getInt("brprice"));
               String slpricek=String.valueOf(rs.getInt("sellingprice"));
               String quantityk=String.valueOf(rs.getInt("quantity"));
               
               String tbdat[]={idk,pnamek ,quantityk,brpricek,slpricek};
              
               tbmodel.addRow(tbdat);
              
           }
            
        }catch(Exception e){
        
    }

       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
//             int v=0;
//         for(int k=0;k<jTable2.getRowCount();k++){
//             int q=Integer.parseInt(jTable2.getValueAt(k, 2).toString());
//                      int s=Integer.parseInt(jTable2.getValueAt(k, 3).toString());
//                      int t=q*s;
//                 
//                      v=v+t;
//         }
        
        
        
        
       int sum=0;
       for(int i=0;i<jTable2.getRowCount();i++){
           sum=sum+Integer.parseInt(jTable2.getValueAt(i, 2).toString());
           
       }
       lbl1.setText(Integer.toString(sum));
//        jLabel4.setText(Integer.toString(v));
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel tbmode2=(DefaultTableModel)jTable2.getModel();
              tbmode2.setRowCount(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String txtbl=txt1.getText();
        int x=Integer.parseInt(txtbl);
         int sum=0;
       for(int i=0;i<jTable2.getRowCount();i++){
           sum=sum+Integer.parseInt(jTable2.getValueAt(i, 2).toString());
           
       }
        int z=x-sum;
         jLabel4.setText(Integer.toString(z));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        Myshop s=new Myshop();
        s.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        Productsreg p=new Productsreg();
        p.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        area.setText("*************************************************\n");
        area.setText(area.getText()+"*                      Shop name                               *\n");
         area.setText(area.getText()+"*************************************************\n");
         Date obj =new Date();
         String date=obj.toString();
           area.setText(area.getText()+"\n"+date+"\n");
          int sum=0;
       for(int i=0;i<jTable2.getRowCount();i++){
           sum=sum+Integer.parseInt(jTable2.getValueAt(i, 2).toString());
                area.setText(area.getText()+"id:"+jTable2.getValueAt(i, 0).toString()+" ");
         area.setText(area.getText()+"name :"+jTable2.getValueAt(i, 1).toString()+"    ");
         area.setText(area.getText()+"price :"+jTable2.getValueAt(i, 2).toString()+"\n");
       }
       
    
         area.setText(area.getText()+"Total:  "+lbl1.getText()+"\n");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        try{
            area.print();
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuActionPerformed
        // TODO add your handling code here:
        try{
         TableModel model1= jTable2.getModel();
        int [] index=jTable2.getSelectedRows();
       Object[] row=new Object[5];
         DefaultTableModel tbmode2=(DefaultTableModel)jTable2.getModel();
       // DefaultTableModel model2=(DefaultTableModel)jTable1.getModel();
        for(int i=0;i<=index.length;i++){
//            row[0]=model1.getValueAt(index[i], 0);
//            row[1]=model1.getValueAt(index[i], 1);
//            
//              row[2]=model1.getValueAt(index[i], 2);
            //model1.setValueAt(i, i, i);
            
            try{
           pst=con.prepareStatement("update proreg set  quantity=quantity+1 where id=?");
           pst.setString(1, model1.getValueAt(index[i], 0).toString());
          
           pst.executeUpdate();
       }catch(Exception e){
           
       }
             
            
            tbmode2.removeRow(index[i]);
        }
        }catch(Exception e){
            
        }
        try{
            pst=con.prepareStatement("select * from proreg");
           ResultSet rs=pst.executeQuery();
            DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
              tbmodel.setRowCount(0);
           while(rs.next()){
               String idk= String.valueOf(rs.getInt("id"));
               String pnamek=rs.getString("pname");
               String brpricek=String.valueOf(rs.getInt("brprice"));
               String slpricek=String.valueOf(rs.getInt("sellingprice"));
               String quantityk=String.valueOf(rs.getInt("quantity"));
               
               String tbdat[]={idk,pnamek ,quantityk,brpricek,slpricek};
              
               tbmodel.addRow(tbdat);
              
           }
            
        }catch(Exception e){
        
    }try{
            pst=con.prepareStatement("select * from proreg");
           ResultSet rs=pst.executeQuery();
            DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
              tbmodel.setRowCount(0);
           while(rs.next()){
               String idk= String.valueOf(rs.getInt("id"));
               String pnamek=rs.getString("pname");
               String brpricek=String.valueOf(rs.getInt("brprice"));
               String slpricek=String.valueOf(rs.getInt("sellingprice"));
               String quantityk=String.valueOf(rs.getInt("quantity"));
               
               String tbdat[]={idk,pnamek ,quantityk,brpricek,slpricek};
              
               tbmodel.addRow(tbdat);
              
           }
            
        }catch(Exception e){
        
    }try{
            pst=con.prepareStatement("select * from proreg");
           ResultSet rs=pst.executeQuery();
            DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
              tbmodel.setRowCount(0);
           while(rs.next()){
               String idk= String.valueOf(rs.getInt("id"));
               String pnamek=rs.getString("pname");
               String brpricek=String.valueOf(rs.getInt("brprice"));
               String slpricek=String.valueOf(rs.getInt("sellingprice"));
               String quantityk=String.valueOf(rs.getInt("quantity"));
               
               String tbdat[]={idk,pnamek ,quantityk,brpricek,slpricek};
              
               tbmodel.addRow(tbdat);
              
           }
            
        }catch(Exception e){
        
    }try{
            pst=con.prepareStatement("select * from proreg");
           ResultSet rs=pst.executeQuery();
            DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
              tbmodel.setRowCount(0);
           while(rs.next()){
               String idk= String.valueOf(rs.getInt("id"));
               String pnamek=rs.getString("pname");
               String brpricek=String.valueOf(rs.getInt("brprice"));
               String slpricek=String.valueOf(rs.getInt("sellingprice"));
               String quantityk=String.valueOf(rs.getInt("quantity"));
               
               String tbdat[]={idk,pnamek ,quantityk,brpricek,slpricek};
              
               tbmodel.addRow(tbdat);
              
           }
            
        }catch(Exception e){
        
    }try{
            pst=con.prepareStatement("select * from proreg");
           ResultSet rs=pst.executeQuery();
            DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
              tbmodel.setRowCount(0);
           while(rs.next()){
               String idk= String.valueOf(rs.getInt("id"));
               String pnamek=rs.getString("pname");
               String brpricek=String.valueOf(rs.getInt("brprice"));
               String slpricek=String.valueOf(rs.getInt("sellingprice"));
               String quantityk=String.valueOf(rs.getInt("quantity"));
               
               String tbdat[]={idk,pnamek ,quantityk,brpricek,slpricek};
              
               tbmodel.addRow(tbdat);
              
           }
            
        }catch(Exception e){
        
    }try{
            pst=con.prepareStatement("select * from proreg");
           ResultSet rs=pst.executeQuery();
            DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
              tbmodel.setRowCount(0);
           while(rs.next()){
               String idk= String.valueOf(rs.getInt("id"));
               String pnamek=rs.getString("pname");
               String brpricek=String.valueOf(rs.getInt("brprice"));
               String slpricek=String.valueOf(rs.getInt("sellingprice"));
               String quantityk=String.valueOf(rs.getInt("quantity"));
               
               String tbdat[]={idk,pnamek ,quantityk,brpricek,slpricek};
              
               tbmodel.addRow(tbdat);
              
           }
            
        }catch(Exception e){
        
    }try{
            pst=con.prepareStatement("select * from proreg");
           ResultSet rs=pst.executeQuery();
            DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
              tbmodel.setRowCount(0);
           while(rs.next()){
               String idk= String.valueOf(rs.getInt("id"));
               String pnamek=rs.getString("pname");
               String brpricek=String.valueOf(rs.getInt("brprice"));
               String slpricek=String.valueOf(rs.getInt("sellingprice"));
               String quantityk=String.valueOf(rs.getInt("quantity"));
               
               String tbdat[]={idk,pnamek ,quantityk,brpricek,slpricek};
              
               tbmodel.addRow(tbdat);
              
           }
            
        }catch(Exception e){
        
    }try{
            pst=con.prepareStatement("select * from proreg");
           ResultSet rs=pst.executeQuery();
            DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
              tbmodel.setRowCount(0);
           while(rs.next()){
               String idk= String.valueOf(rs.getInt("id"));
               String pnamek=rs.getString("pname");
               String brpricek=String.valueOf(rs.getInt("brprice"));
               String slpricek=String.valueOf(rs.getInt("sellingprice"));
               String quantityk=String.valueOf(rs.getInt("quantity"));
               
               String tbdat[]={idk,pnamek ,quantityk,brpricek,slpricek};
              
               tbmodel.addRow(tbdat);
              
           }
            
        }catch(Exception e){
        
    }try{
            pst=con.prepareStatement("select * from proreg");
           ResultSet rs=pst.executeQuery();
            DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
              tbmodel.setRowCount(0);
           while(rs.next()){
               String idk= String.valueOf(rs.getInt("id"));
               String pnamek=rs.getString("pname");
               String brpricek=String.valueOf(rs.getInt("brprice"));
               String slpricek=String.valueOf(rs.getInt("sellingprice"));
               String quantityk=String.valueOf(rs.getInt("quantity"));
               
               String tbdat[]={idk,pnamek ,quantityk,brpricek,slpricek};
              
               tbmodel.addRow(tbdat);
              
           }
            
        }catch(Exception e){
        
    }try{
            pst=con.prepareStatement("select * from proreg");
           ResultSet rs=pst.executeQuery();
            DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
              tbmodel.setRowCount(0);
           while(rs.next()){
               String idk= String.valueOf(rs.getInt("id"));
               String pnamek=rs.getString("pname");
               String brpricek=String.valueOf(rs.getInt("brprice"));
               String slpricek=String.valueOf(rs.getInt("sellingprice"));
               String quantityk=String.valueOf(rs.getInt("quantity"));
               
               String tbdat[]={idk,pnamek ,quantityk,brpricek,slpricek};
              
               tbmodel.addRow(tbdat);
              
           }
            
        }catch(Exception e){
        
    }try{
            pst=con.prepareStatement("select * from proreg");
           ResultSet rs=pst.executeQuery();
            DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
              tbmodel.setRowCount(0);
           while(rs.next()){
               String idk= String.valueOf(rs.getInt("id"));
               String pnamek=rs.getString("pname");
               String brpricek=String.valueOf(rs.getInt("brprice"));
               String slpricek=String.valueOf(rs.getInt("sellingprice"));
               String quantityk=String.valueOf(rs.getInt("quantity"));
               
               String tbdat[]={idk,pnamek ,quantityk,brpricek,slpricek};
              
               tbmodel.addRow(tbdat);
              
           }
            
        }catch(Exception e){
        
    }try{
            pst=con.prepareStatement("select * from proreg");
           ResultSet rs=pst.executeQuery();
            DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
              tbmodel.setRowCount(0);
           while(rs.next()){
               String idk= String.valueOf(rs.getInt("id"));
               String pnamek=rs.getString("pname");
               String brpricek=String.valueOf(rs.getInt("brprice"));
               String slpricek=String.valueOf(rs.getInt("sellingprice"));
               String quantityk=String.valueOf(rs.getInt("quantity"));
               
               String tbdat[]={idk,pnamek ,quantityk,brpricek,slpricek};
              
               tbmodel.addRow(tbdat);
              
           }
            
        }catch(Exception e){
        
    }try{
            pst=con.prepareStatement("select * from proreg");
           ResultSet rs=pst.executeQuery();
            DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
              tbmodel.setRowCount(0);
           while(rs.next()){
               String idk= String.valueOf(rs.getInt("id"));
               String pnamek=rs.getString("pname");
               String brpricek=String.valueOf(rs.getInt("brprice"));
               String slpricek=String.valueOf(rs.getInt("sellingprice"));
               String quantityk=String.valueOf(rs.getInt("quantity"));
               
               String tbdat[]={idk,pnamek ,quantityk,brpricek,slpricek};
              
               tbmodel.addRow(tbdat);
              
           }
            
        }catch(Exception e){
        
    }try{
            pst=con.prepareStatement("select * from proreg");
           ResultSet rs=pst.executeQuery();
            DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
              tbmodel.setRowCount(0);
           while(rs.next()){
               String idk= String.valueOf(rs.getInt("id"));
               String pnamek=rs.getString("pname");
               String brpricek=String.valueOf(rs.getInt("brprice"));
               String slpricek=String.valueOf(rs.getInt("sellingprice"));
               String quantityk=String.valueOf(rs.getInt("quantity"));
               
               String tbdat[]={idk,pnamek ,quantityk,brpricek,slpricek};
              
               tbmodel.addRow(tbdat);
              
           }
            
        }catch(Exception e){
        
    }try{
            pst=con.prepareStatement("select * from proreg");
           ResultSet rs=pst.executeQuery();
            DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
              tbmodel.setRowCount(0);
           while(rs.next()){
               String idk= String.valueOf(rs.getInt("id"));
               String pnamek=rs.getString("pname");
               String brpricek=String.valueOf(rs.getInt("brprice"));
               String slpricek=String.valueOf(rs.getInt("sellingprice"));
               String quantityk=String.valueOf(rs.getInt("quantity"));
               
               String tbdat[]={idk,pnamek ,quantityk,brpricek,slpricek};
              
               tbmodel.addRow(tbdat);
              
           }
            
        }catch(Exception e){
        
    }try{
            pst=con.prepareStatement("select * from proreg");
           ResultSet rs=pst.executeQuery();
            DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
              tbmodel.setRowCount(0);
           while(rs.next()){
               String idk= String.valueOf(rs.getInt("id"));
               String pnamek=rs.getString("pname");
               String brpricek=String.valueOf(rs.getInt("brprice"));
               String slpricek=String.valueOf(rs.getInt("sellingprice"));
               String quantityk=String.valueOf(rs.getInt("quantity"));
               
               String tbdat[]={idk,pnamek ,quantityk,brpricek,slpricek};
              
               tbmodel.addRow(tbdat);
              
           }
            
        }catch(Exception e){
        
    }try{
            pst=con.prepareStatement("select * from proreg");
           ResultSet rs=pst.executeQuery();
            DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
              tbmodel.setRowCount(0);
           while(rs.next()){
               String idk= String.valueOf(rs.getInt("id"));
               String pnamek=rs.getString("pname");
               String brpricek=String.valueOf(rs.getInt("brprice"));
               String slpricek=String.valueOf(rs.getInt("sellingprice"));
               String quantityk=String.valueOf(rs.getInt("quantity"));
               
               String tbdat[]={idk,pnamek ,quantityk,brpricek,slpricek};
              
               tbmodel.addRow(tbdat);
              
           }
            
        }catch(Exception e){
        
    }
        
 
       
    }//GEN-LAST:event_btnuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton btnu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JTextField txt1;
    // End of variables declaration//GEN-END:variables
}
